on:
  push:
    branches:
      - main
env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_CHANGE_ARCH_TO_ARM: 1
jobs:
  bottle:
    strategy:
      matrix:
        include:
          - runner: macos-12
          - runner: macos-11
          - runner: macos-10.15
          - runner: macos-12-arm64
          - runner: macos-11-arm64
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        working-directory: ${{matrix.workdir || github.workspace}}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Set environment variables
        if: runner.os == 'macOS'
        run: echo 'PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin' >> $GITHUB_ENV

      - name: Set up Homebrew
        id: set-up-homebrew
        if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Xcode
        if: runner.os == 'macOS'
        run: |
          if [ "${{ matrix.runner }}" = "macos-10.15" ]; then
            sudo xcode-select -s /Applications/Xcode_11.7.app || exit 1
          else
            latest_stable_xcode_path="$(find -E /Applications -maxdepth 1 -regex '.*Xcode_13.[0-9]+.app' | sort -V | tail -1)"
            sudo xcode-select -s "$latest_stable_xcode_path" || exit 1
          fi

      - name: Print debug information
        run: system_profiler SPSoftwareDataType

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup
